name: setXP
main: me.ellbristow.setXP.setXP
version: 1.2
author: ellbristow
description: >
             Set player's experience level
commands:
  setxp:
    description: Set XP to requested level
    permission: setxp.setxp
    usage: |
      /<command> {player} [level]
      /<command> add {player} [levels]
  getxp:
    description: Check player's current XP level
    permission: setxp.getxp
    usage: "/<command> [player]"
permissions:
  setxp.*:
    description: Access to all setXP commands
    children:
      setxp.setxp: true
      setxp.setxp.others: true
      setxp.getxp: true
      setxp.exempt: false
      setxp.override: true
      setxp.add: true
      setxp.add.others: true
  setxp.setxp:
    description: Access to /setxp
  setxp.setxp.others:
    description: Can set other players' XP level
  setxp.exempt:
    description: Other players cannot change this players XP level
  setxp.override:
    description: Player can override exemption
  setxp.getxp:
    description: Access to /getxp
  setxp.add:
    description: Can add to own XP level
  setxp.add.others:
    description: Can add to another player's XP level
